//
// Created by wowan on 31.03.2024.
//

#ifndef C_PLUS_PLUS_CHERNIVTSY_ACADEMY_SIMPLE_SENTENCES_H
#define C_PLUS_PLUS_CHERNIVTSY_ACADEMY_SIMPLE_SENTENCES_H


class Simple_sentences {

};


#endif //C_PLUS_PLUS_CHERNIVTSY_ACADEMY_SIMPLE_SENTENCES_H
